name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace secret
        run: |
          sed -i "s/YOUR_JAVASCRIPT_KEY/${{ secrets.YOUR_JAVASCRIPT_KEY }}/g" index.html
          sed -i "s/YOUR_REST_API_KEY/${{ secrets.YOUR_REST_API_KEY }}/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
